### ISSUE TITLE
List of References

### ISSUE THREAD

**Issue by marbetschar** [haroldtreen/epub-press-clients#12]
Is it possible to add a list of references to all article URL's at the end of the book?

**Comment by haroldtreen** [comment]
Oooo. Like a final chapter that just says all the links in the book? That's an awesome idea!

Shouldn't be too hard to add.

**Comment by marbetschar** [comment]
Do you think we can add the list of references somewhen in the near future? Currently I'm super happy with the Safari and EpubPress integration.

The only two issues I'm eagerly waiting for is this one and [the authors meta data](https://github.com/haroldtreen/epub-press-clients/issues/14) - so if we can fix those that would be f*cking awesome!!!

**Comment by haroldtreen** [comment]
Sooo... I'm currently in the middle of a move and all kinds of busyness which has made it hard to find time for these things...

BUT...when I saw all your progress I was too inspired to delay these things.

Just pushed up the change for adding references! 🎉 
And `author` should now be an accepted piece of metadata.

I hope you find both these changes f*cking awesome ;).

![image](https://cloud.githubusercontent.com/assets/1745854/24829278/a64cf332-1c3c-11e7-9500-6af983860bfd.png)
![image](https://cloud.githubusercontent.com/assets/1745854/24829282/ae3a4694-1c3c-11e7-88a7-06111b76ed7c.png)

Thanks for all the suggestions!

**Comment by marbetschar** [comment]
Awesome!!!!!!!!!!!!!! Thank you so much!! 😍😍😍😍😍😍
