### ISSUE TITLE
file title in unknown | kindle

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [haroldtreen/epub-press-clients#124]
when I save file ( send to kindle email) I got unknown title

**Comment by haroldtreen** [comment]
Hey @MoatazAbdAlmageed 

This might be a known issue? 

https://github.com/haroldtreen/epub-press-clients/blob/master/packages/epub-press-js/README.md#issues

When using the package on Safari it downloads the file as "Unkown". When you rename the file with the proper extension it should fix the issue though 👍.

Hope this helps.

**Comment by MoatazAbdAlmageed** [comment]
I send it to **kindle** email not to download also I'm using chrome on macos

**Comment by MoatazAbdAlmageed** [comment]
Also I tested it in linux (chrome&firefox) I got unknown titlte if I add email with epub

**Comment by MoatazAbdAlmageed** [comment]
> I send it to kindle email not to download also I'm using chrome on macos

I got an unknown name in my **kindle**, It was working like 10 days before !!

**Comment by haroldtreen** [comment]
I believe someone else is seeing this too, but it appears to be a bug with how Amazon is handling Epubs :/.

https://www.fivefilters.org/2022/kindle-epub-issues/

EpubPress has been unchanged for quite some time, so any breakages are likely with the external tools.

Sorry there's not a more actionable fix for this :(
