### ISSUE TITLE
Meta data

### ISSUE THREAD

**Issue by marbetschar** [haroldtreen/epub-press-clients#14]
Can we set the Author of the Book to the article Author instead of "ePub.Press"? Maybe only, if only one article is converted?

If you'd like to keep ePub.Press in the meta data, there's a Field something like "creator" which contains the app created the book.

**Comment by haroldtreen** [comment]
Definitely! Additional metadata is something worth adding.

Ahaha, I've fallen so behind because of other work but all these ideas are really getting me eager to put more love into this :).

Thanks @marbetschar !

**Comment by marbetschar** [comment]
Since the Safari Extension is in place now and nearly everything works like a charm, I would really love to see the articles author taken as author for the eBook instead of EpubPress. At least, if there is only one article converted and this is taken from a URL.

In my opinion using EpubPress as author of the book should only be taken as last resort. What's your opinion on this?

**Comment by haroldtreen** [comment]
I just updated the backend so that it will accept an author 🎉 !

Just add `author` as a key in the request body similar to `title` and `description`.

Let me know if that solves this issue and we can call it closed :).

**Comment by marbetschar** [comment]
Works like a charm - thank you!!!!! 😍😍😍😍😍😍
