### ISSUE TITLE
Various images sometimes missing from output

### ISSUE THREAD

**Issue by emtilt** [haroldtreen/epub-press-clients#21]
Sometimes various images are missing from generated ebooks. I encountered this while trying to convert all of the chapters/sections of [Tempest: Geometries of Play](http://quod.lib.umich.edu/cgi/t/text/text-idx?cc=lvg;c=lvg;idno=13030180.0001.001;rgn=full%20text;view=toc;xc=1;g=dculture) to an epub. After opening all pages in tabs, selecting them in epubpress, and generating, some images are present in the output but some are not. Which ones are present or missing varies on each attempt. I've seen this issue occur with several different websites. Perhaps epubpress is exceeding some servers' maximum concurrent connections or something so some images timeout?

**Comment by haroldtreen** [comment]
Hey @emtilt!

Thanks for reaching out. Sorry for the delay.

That's really interesting...

My first thought was that the page was exceeding EpubPress's image limits (the server limits the number of images it will download).
What you are saying could also be true - I'm noticing that images are all downloading concurrently and that could be hitting limits for the server.

For example, just browsing around the site you provided caused this to appear:

![image](https://user-images.githubusercontent.com/1745854/27894163-88eb68be-61d8-11e7-96ad-bc4ae9e82884.png)

So it looks like this site is throttling how many requests can be made (I was just browsing, let alone trying to download a ton of stuff at once).

I'll have to dig around deeper, but I think a first step will be throttling the number of requests EpubPress is making.

**Comment by haroldtreen** [comment]
I've pushed an update to limit the number of concurrent downloads happening. This should hopefully reduce the likelihood of triggering rate limiting. 

Let me know if you notice any changes. In my testing, it looks like more content is getting downloaded from the site you provided. 👍 

Will close this and re-open if more action items can be determined.
