### ISSUE TITLE
Where's the donate button?

### ISSUE THREAD

**Issue by RickCarlino** [haroldtreen/epub-press-clients#3]
I would like to support the project and have some Bitcoin. Do you accept donations?

**Comment by haroldtreen** [comment]
Wow! Thanks @RickCarlino! 😃 

I would love to accept donations but haven't set anything up. Is there a system you would suggest? I've never set anything up before. I'll have to look into it!
Sorry for the delayed response. I only just noticed a new issue had been added :P.

**Comment by haroldtreen** [comment]
Added a section on the site for making contributions! :)

https://epub.press/#donate

Awesome to have people wanting to help out! Would love to be able to direct more attention to this. 
Thanks all ❤️

**Comment by RickCarlino** [comment]
@haroldtreen Just sent a donation. Thanks for all your work on this project.

Nothing else does a good job at providing me offline documentation I can use on my e-reader, so I appreciate all of your hard work.

**Comment by haroldtreen** [comment]
Thanks so much @RickCarlino! :D

Even just words of support, tweets, reviews - all of it is so appreciate! 
I've been accepted into the [Recurse Center](https://www.recurse.com/) and plan to work on EpubPress related projects/open source libraries for 3 months in New York city. 

![image](https://cloud.githubusercontent.com/assets/1745854/16606591/d546aaa6-42fe-11e6-8b1f-cab47abf8f7b.png)

Excited to hear people are willing to donate. I'll be putting it towards my 3 months of unpaid hacking/living in New York 👍 .

Thanks again!
