### ISSUE TITLE
Support for RTL Languages

### ISSUE THREAD

**Issue by seefood** [haroldtreen/epub-press-clients#32]
Hey there, What an excellent add-on! I found it yesterday on the Mozilla site.

I see that content I create from an article in Hebrew comes out aligned to the left rather than the right, which I guess means that the directionality of the text is not extracted and preserved from the DOM when creating the epub. I didn't dive into the code yet, but I bet it should be an easy one to fix if the code already looks for other local and global settings like it for indentations and the like.

In case I can't find the place and submit a PR (JS is not my forte, I'm an infrastructure guy), I'm also leaving here this item, in case anyone else can pick this up.

Thanks!

**Comment by seefood** [comment]
I see this is actually happening in the backend. I'll move the issue to the correct repo.

**Comment by yazix100** [comment]
Hi seefood, 

i'm having the same issue with arabic, can you please tell me how you corrected the issue?

Thank you.

**Comment by seefood** [comment]
Didn't solve it, moved it over here: https://github.com/haroldtreen/epub-press/issues/10
