### ISSUE TITLE
.mobi file always gets the default title

### ISSUE THREAD

**Issue by SuzanaK** [haroldtreen/epub-press-clients#55]
I'm using the Firefox add-on and download the files as `.mobi`. Even though I set a title in the add-on, I always get an ebook with the default title ("EpubPress" and then the date) that I have to adapt manually in Calibre.

**Comment by SuzanaK** [comment]
Sorry I tried again today and it worked perfectly. Don't know what went wrong the other day, I tested it several times. Closing the issue. And thanks for the great addon, it's extremely useful for me.

**Comment by adhamsalama** [comment]
The issue happens to me.
