### ISSUE TITLE
why did we had the size limitations of EpubPress?

### ISSUE THREAD

**Issue by mars00772** [haroldtreen/epub-press-clients#80]
why did we had the limitations of EpubPress?
Books are limited to containing 50 articles.
Books must be 10 Mb or less for email delivery to work.
Images in an article must be 1 Mb or less. Images that exceed this limit will be removed.
No more than 30 images will be downloaded.

**Comment by haroldtreen** [comment]
Hey - the limits are just to simplify running the service. The extension and service are offered for free and I cover all the expenses out of my own pocket. To keep expenses low I use a cheap server, but if everyone was allowed to download as much as they wanted it would require something more expensive.

Maybe one day I'll work on a paid tier without limits - but haven't gotten to it!

In the meantime, all the code is available and bundled in a way that should be pretty easy to run locally. Doing that and changing the limits is an option if you're looking to get more out of the service. 

Hope that helps!
