### ISSUE TITLE
Generate Cover Image w/ Book Titles

### ISSUE THREAD

**Issue by haroldtreen** [haroldtreen/epub-press-clients#9]
Currently, every book is given the exact same cover image. This makes it difficult to distinguish books from each other.

Solution: Add the title to each cover image so that books are distinguishable by the cover.

**Comment by marbetschar** [comment]
As idea: You might also consider adopting the [Open Graph protocol](http://ogp.me/) information to enrich the cover: For example using the `og:image` as cover image.

**Comment by haroldtreen** [comment]
Interesting. This could probably be done even easier. I haven't tested if Facebook looks at any of this metadata if you were to upload a book.

Will investigate!

**Comment by marbetschar** [comment]
Interesting idea; adding Open Graph to a ePub was not my original idea, but why not :)

For clarification: Originaly I thought of just grabbing this info from the web, like Facebook does, to create a beautiful cover which reflects the books content.

**Comment by haroldtreen** [comment]
Oh! That's super smart too. 

I actually contributed a change like that to the underlying readability library that is used (see https://github.com/luin/readability/commit/07ac5ffda8e1455cafc3efcf2388d061dff99326).

Not sure the best way to select one image...I suppose it could be a mosaic with all images... now I'm more intrigued.

So many exciting things to add :D.

**Comment by marbetschar** [comment]
😁 - This sounds amazing!!

To kick things off I think adding the image of the first article is enough. I read a lot in iBooks on my iPhone and right now it's hard to distuingish the books on the small screen.

So adding just one image is already a HUGE gain for me.

**Comment by marbetschar** [comment]
till this is implemented, is it possible to drop the cover image completely?

At least in iBooks, if the cover image is missing it is created dynamically providing the content title & author:

<img width="160" alt="bildschirmfoto 2017-04-04 um 18 04 16" src="https://cloud.githubusercontent.com/assets/392542/24666637/323629ce-1961-11e7-96aa-f72e045e0138.png">

This means, the books are distinguishable one to another. If the cover image is set by ePub.press, there is no chance to distinguish the books without opening them:

<img width="197" alt="bildschirmfoto 2017-04-04 um 18 06 34" src="https://cloud.githubusercontent.com/assets/392542/24666739/7b56c190-1961-11e7-8c57-dbccb6a9ac7b.png">

**Comment by marbetschar** [comment]
FYI: Due to the issue above, I'm currently removing the cover in my Safari Extension by deleting the following files:

```
/epub/root/dir/OEBPF/cover.xhtml
/epub/root/dir/OEBPF/images/cover.png
```

And by removing the following references in the `/epub/root/dir/OEBPF/ebook.opf`:

```
/manifest/item[id="cover-image"]
/manifest/item[id="cover"]
/spine/itemref[idref="cover"]
```

Opens in iBooks without any problems. Of course it would be better if the cover would be enriched with some distinguishable content - but as iBooks generates a dynamic cover based upon the books meta data I'm fine with that for now.

**Comment by haroldtreen** [comment]
This has been done! Hope y'all enjoy it :)

![image](https://user-images.githubusercontent.com/1745854/32140751-504ddc16-bc42-11e7-825d-9528de4b0808.png)
